language: node_js

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install: yarn --frozen-lockfile

cache:
  yarn: true
  directories:
    - 'node_modules'

script:
  - yarn lint
  - yarn test && codecov
